version: "3.9"
services:
  buildbot:
    image: tobiichiorigami/tinderbox-cluster:latest
    ports:
      - "8010:8010"
      - "9989:9989"
    links:
      - postgresql:db
    depends_on:
      - postgresql
  postgresql:
    image: postgres-buildbot
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=riscv"
  # admin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - postgresql:db
  #   depends_on:
  #     - postgresql
  #   environment:
  #     - "PGADMIN_DEFAULT_EMAIL=myloveyuxuan@gmail.com"
  #     - "PGADMIN_DEFAULT_PASSWORD=riscv"
